### ISSUE TITLE
Deprecate TcMenu embed forms / UI

### ISSUE THREAD

**Issue by vzahradnik** [TcMenu/tcMenu#522]
**Is your feature request related to a problem? Please describe.**
Since TcMenu is developed by a handful of people, it doesn't make sense to build large features like own embedded UI designer. Instead we should keep the code simple and allow extensibility, e.g. by allowing new integrations or leveraging native UI libraries in the mobile apps and web. As these libraries are maintained by bigger teams for us.

**Describe the solution you'd like**
Deprecate this feature and remove it from the code. The support is in our Flutter package, Java app and TcMenuLib.

**Comment by davetcc** [comment]
Sometimes you've got to admit that you've made a mistake, and the embedded forms were one the biggest, they detracted from TcMenu stability and network connectivity for at least six months. The plan is as can be seen from the open issues to proceed two-fold.

1. provide an open-source dart/Flutter API with a starting point app. It will be trivial to modify this app to meet your needs and deploy to an App Store. There will be reasonable limits around how it can be deployed in the license, but it will otherwise be completely usable.
2. provide integration to many cloud and home systems, including MQTT
3. look into providing a lighter weight Javascript based application that can be served from larger boards.
